language: php

env:
  - SILEX_VERSION="1.2.*"

before_script:
  - composer require silex/silex:${SILEX_VERSION}
  - composer install --dev --prefer-source

script: vendor/bin/phpunit

sudo: false # use Docker in Travis, see http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

php:
  - 5.4
  - 5.5
  - 5.6
